version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_minishop
    ports:
      - "8000:8000"
    volumes:
      - minishop:/data/web
    environment:
      - ENV=production
volumes:
  minishop:
    driver: local